blocks:
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: amazing druid
  retry_config: null
  status: updated
  timeout: null
  type: scratchpad
  upstream_blocks: []
  uuid: amazing_druid
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - elven_healer
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: utopian surf
  retry_config: null
  status: executed
  timeout: null
  type: data_loader
  upstream_blocks: []
  uuid: utopian_surf
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - crystal_rogue
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: elven healer
  retry_config: null
  status: executed
  timeout: null
  type: transformer
  upstream_blocks:
  - utopian_surf
  uuid: elven_healer
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: crystal rogue
  retry_config: null
  status: executed
  timeout: null
  type: data_exporter
  upstream_blocks:
  - elven_healer
  uuid: crystal_rogue
cache_block_output_in_memory: false
callbacks: []
concurrency_config: {}
conditionals: []
created_at: '2024-11-22 19:31:15.560189+00:00'
data_integration: null
description: null
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: original_prometheus_generator
notification_config: {}
remote_variables_dir: null
retry_config: {}
run_pipeline_in_one_process: false
settings:
  triggers: null
spark_config: {}
tags: []
type: python
uuid: original_prometheus_generator
variables_dir: /home/src/mage_data/default_repo
widgets: []
