global:
  scrape_interval: 15s

scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets:
    - localhost:9090
- job_name: "demo"
  static_configs:
  - targets:
    - demo.promlabs.com:10000
    - demo.promlabs.com:10001
    - demo.promlabs.com:10002
- job_name: 'mageai'
  static_configs:
  - targets:
    - 'host.docker.internal:6789'
- job_name: 'mageai-prom-server'
  static_configs:
  - targets:
    - 'mage-ai:8000'
- job_name: 'local-prom-server'
  static_configs:
  - targets:
    - 'localhost:8000'
    - 'host.docker.internal:8000'
