services:
  kafka:
    image: apache/kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    ports:
      - '9092:9092'
      - '29092:29092'
    container_name: kafka-broker

  mage:
    image: elestio/mage-ai:latest
    restart: unless-stopped
    # environment:
      # - REQUIRE_USER_AUTHENTICATION=1
    volumes:
      - "./mage:/home/src"
    ports:
      - '6789:6789'
    container_name: mage-ai
  
  kafka-consumer:
    build:
      context: .
    volumes:
      - ./student_grades.db:/path/to/your/project/directory/student_grades.db
    depends_on:
      - kafka
